[env:ttgo-t-beam]
platform = espressif32
board = ttgo-t-beam
framework = arduino
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib @ ^6.5.0  ; For P2P LoRa communication with SX1262
    lewisxhe/XPowersLib @ ^0.1.5 ; For AXP192/AXP2101 PMIC
build_flags =
    -I include
    ; -D RADIOLIB_DEBUG  ; Uncomment for RadioLib debug messages
    ; -D RADIOLIB_VERBOSE ; Uncomment for RadioLib verbose debug messages

    ; --- OPTIONAL LOW POWER FLAGS (Use with caution) ---
    ; Disable Brownout Detector for potentially lower power.
    ; Test thoroughly as it can lead to instability if voltage drops too low.
    ; -D CONFIG_ESP32_BROWNOUT_DET=0

upload_speed = 921600

; Serial Monitor filter
; monitor_filters = esp32_exception_decoder, default
; monitor_filters = direct ; To see raw output
